redmine:
  db: redmine:redmine@tcp(0.0.0.0:3306)/redmine # things from docker-compose
  url: "http://localhost:10083"
  api_key: "2159cef2fb6c82c4f66981f199798781e161c694"
  repositories: "/var/repositories/"

project:
  id: "my-project"
  name: "My Project"
  description: "This is a sample project x."
  git_path: "/test/.git"
  wiki: |
    # My Project
    This is a sample project.
    More text
    
    And a bit more.

workflow:
  states:
    Backlog:
      description: Product backlog with user stories.
      ai: False
    To Do:
      description: Tasks selected for the current sprint.
      prompt: Split Story task into smaller chunks or start working on a task.
      ai: True
      is_default: True
    In Progress:
      description: Tasks currently being worked on.
      ai: True
    Testing:
      description: Tasks undergoing testing.
      ai: False
    Rejected:
      description: Tasks rejected during testing.
      ai: True
    Done:
      description: Completed tasks.
      ai: False
      is_closed: True

  transitions:
    - source: Backlog
      target: To Do
    - source: To Do
      target: In Progress
    - source: In Progress
      target: Testing
    - source: Testing
      target: Done
    - source: Testing
      target: Rejected
    - source: Rejected
      target: In Progress
    - source: Testing
      target: To Do
    - source: Done
      target: To Do

  issue_types:
    Task:
      description: A task that needs to be done.
      jobs:
        In Progress:
          steps:
            - aider: architect
              prompt: Analyze given task carefully and locate files that need to be worked on.
            - aider: coder
              prompt: Implement it
    Story:
      description: A user story.
      jobs:
        In Progress:
          steps:
            - aider: architect
              prompt: Analyze given task carefully and locate files that need to be worked on.
            - aider: ask
              prompt: Implement it
            - aider: coder
              prompt: Implement necessary changes
