services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - redmine_network

  database: &database_base
    image: mariadb:11.2
    environment:
      - MARIADB_USER=redmine
      - MARIADB_PASSWORD=redmine
      - MARIADB_DATABASE=redmine
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_AUTO_UPGRADE=1
    ports:
      - "3306:3306"
    depends_on:
      - phpmyadmin
#    volumes:
#      - database_data:/var/lib/mysql
    command:
      - mariadbd
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - redmine_network

  redmine_template: &redmine_base
    build: ./docker-redmine/
    image: sameersbn/redmine:6.0.2
    env_file:
      - .redmine.env
    ports:
      - "10083:80"  # use different ports for each instance
#    depends_on:
#      - database
    #volumes:
      #- ./data/redmine_logs:/var/log/redmine
      #- ./repositories:/var/repositories  # This will be overridden in each instance
    networks:
      - redmine_network

# LCO project
  redmine-lco:
    <<: *redmine_base
    environment:
      - DB_HOST=database-lco
    volumes:
#      - ./data/redmine/data:/home/redmine/data
      - /home/astepanovs/rubik/lounge-campaign-orchestrator:/var/repositories/lco
    depends_on:
      - database-lco

  database-lco:
    <<: *database_base
    volumes:
      - database_data_lco:/var/lib/mysql

#  dev:
#    build:
#      context: agents/
#      dockerfile: Dockerfile
#    volumes:
#      - ./www:/var/www
#    tty: true
#    stdin_open: true
#    container_name: ubuntu-dev
#    hostname: ubuntu-dev
#    networks:
#      - redmine_network
#    depends_on:
#      - redmine
#    command: tail -f /dev/null
#    environment:
#      - TERM=xterm-256color
#      - SHELL=/bin/zsh
#      - CODER_REDMINE_API_KEY=${CODER_REDMINE_API_KEY}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
#      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
#      - REDMINE_URL=http://redmine
#
#      - REDMINE_ARCHITECT_LOGIN=${REDMINE_ARCHITECT_LOGIN}
#      - REDMINE_ARCHITECT_PASSWORD=${REDMINE_ARCHITECT_PASSWORD}
#      - REDMINE_ARCHITECT_API_KEY=${REDMINE_ARCHITECT_API_KEY}
#
#      - REDMINE_CODER_LOGIN=${REDMINE_CODER_LOGIN}
#      - REDMINE_CODER_PASSWORD=${REDMINE_CODER_PASSWORD}
#      - REDMINE_CODER_API_KEY=${REDMINE_CODER_API_KEY}
#
#      - REDMINE_CODER_JUNIOR_LOGIN=${REDMINE_CODER_JUNIOR_LOGIN}
#      - REDMINE_CODER_JUNIOR_PASSWORD=${REDMINE_CODER_JUNIOR_PASSWORD}
#      - REDMINE_CODER_JUNIOR_API_KEY=${REDMINE_CODER_JUNIOR_API_KEY}
#
#      - LM_STUDIO_API_BASE=${LM_STUDIO_API_BASE}
#      - LM_STUDIO_API_KEY=${LM_STUDIO_API_KEY}
#      - OLLAMA_API_BASE=${OLLAMA_API_BASE}

networks:
  redmine_network:
    driver: bridge

volumes:
  database_data_lco:

