services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - redmine_network

  database: &database_base
    image: mariadb:11.2
    environment:
      - MARIADB_USER=redmine
      - MARIADB_PASSWORD=redmine
      - MARIADB_DATABASE=redmine
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_AUTO_UPGRADE=1
    ports:
      - "3306:3306"
    depends_on:
      - phpmyadmin
#    volumes:
#      - database_data:/var/lib/mysql
    command:
      - mariadbd
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - redmine_network

  redmine_template: &redmine_base
    build: ./docker-redmine/
    image: sameersbn/redmine:6.0.3
    env_file:
      - .redmine.env
    ports:
      - "10083:80"  # use different ports for each instance
#    depends_on:
#      - database
    #volumes:
      #- ./data/redmine_logs:/var/log/redmine
      #- ./repositories:/var/repositories  # This will be overridden in each instance
    networks:
      - redmine_network

  andai_template: &andai_base
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./www:/var/www
    image: andai:latest # build it first with `make build-docker`
    tty: true
    stdin_open: true
    networks:
      - redmine_network
    command: ["nothing", "execute"] # sleep infinity
    environment:
      - TERM=xterm-256color
      - SHELL=/bin/zsh
      - PROJECT=test

#      - CODER_REDMINE_API_KEY=${CODER_REDMINE_API_KEY}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
#      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
#      - REDMINE_URL=http://redmine
#
#      - REDMINE_ARCHITECT_LOGIN=${REDMINE_ARCHITECT_LOGIN}
#      - REDMINE_ARCHITECT_PASSWORD=${REDMINE_ARCHITECT_PASSWORD}
#      - REDMINE_ARCHITECT_API_KEY=${REDMINE_ARCHITECT_API_KEY}
#
#      - REDMINE_CODER_LOGIN=${REDMINE_CODER_LOGIN}
#      - REDMINE_CODER_PASSWORD=${REDMINE_CODER_PASSWORD}
#      - REDMINE_CODER_API_KEY=${REDMINE_CODER_API_KEY}
#
#      - REDMINE_CODER_JUNIOR_LOGIN=${REDMINE_CODER_JUNIOR_LOGIN}
#      - REDMINE_CODER_JUNIOR_PASSWORD=${REDMINE_CODER_JUNIOR_PASSWORD}
#      - REDMINE_CODER_JUNIOR_API_KEY=${REDMINE_CODER_JUNIOR_API_KEY}
#
#      - LM_STUDIO_API_BASE=${LM_STUDIO_API_BASE}
#      - LM_STUDIO_API_KEY=${LM_STUDIO_API_KEY}
#      - OLLAMA_API_BASE=${OLLAMA_API_BASE}


# LCO project
  database-lco:
    <<: *database_base
    volumes:
      - database_data_lco:/var/lib/mysql

  redmine-lco:
    <<: *redmine_base
    environment:
      - DB_HOST=database-lco
    volumes:
#      - ./data/redmine/data:/home/redmine/data
      - /home/astepanovs/rubik/lounge-campaign-orchestrator:/var/repositories/lco
    depends_on:
      - database-lco

# Grappler project
  database-grappler:
    <<: *database_base
    volumes:
      - database_data_grappler:/var/lib/mysql

  redmine-grappler:
    <<: *redmine_base
    environment:
      - DB_HOST=database-grappler
    volumes:
      - /home/astepanovs/go/src/grappler:/var/repositories/grappler
    depends_on:
      - database-grappler

# AndAI project
  database-andai:
    <<: *database_base
    volumes:
      - database_data_andai:/var/lib/mysql

  redmine-andai:
    <<: *redmine_base
    environment:
      - DB_HOST=database-andai
    volumes:
      - /home/astepanovs/andaicpy/andai:/var/repositories/andai
    depends_on:
      - database-andai

# Streamlit project
  database-streamlit:
    <<: *database_base
    volumes:
      - database_data_streamlit:/var/lib/mysql

  redmine-streamlit:
    <<: *redmine_base
    environment:
      - DB_HOST=database-streamlit
    volumes:
      - /home/astepanovs/www/streamlit-proto:/var/repositories/streamlit
    depends_on:
      - database-streamlit

# Test project
  database-test:
    <<: *database_base
    volumes:
      - database_data_test:/var/lib/mysql

  redmine-test:
    <<: *redmine_base
    environment:
      - DB_HOST=database-test
    volumes:
      - /tmp/test:/var/repositories/test
    depends_on:
      - database-test

  andai-test:
    <<: *andai_base
    environment:
      - PROJECT=test
    volumes:
      - /tmp/test:/var/repositories/test
    depends_on:
      - redmine-test

networks:
  redmine_network:
    driver: bridge

volumes:
  database_data_lco:
  database_data_test:
  database_data_grappler:
  database_data_andai:
  database_data_streamlit:

