x-project-volumes: &project-volumes
  - /tmp/test-repo/:/var/repositories/test-repo      # <-- replace with your actual project paths. First path is your local system path.
  - ./:/app/ # config files are located here. Used if running andai in docker.

services:
  database:
    image: mariadb:11.2
    env_file:
      - .redmine.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      - mariadbd
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redmine:
    image: sameersbn/redmine:6.0.4-1
    # (!) If you are running ARM (Mac), then
    # you will need to build this image yourself (or ask https://github.com/sameersbn/docker-redmine owner to include it in docker hub)
    #
    # Should be as simple as:
    # cd /tmp
    # git clone https://github.com/sameersbn/docker-redmine.git
    # cd docker-redmine
    # docker build -t sameersbn/redmine:6.0.4-1 .

    env_file:
      - .redmine.env
    ports:
      - "10083:80"
    volumes: *project-volumes
    depends_on:
      - database

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/database
      o: bind
